### ISSUE TITLE
[Feature request] Make artemis commands use an expandable box when there's too much data

### ISSUE THREAD

**Issue by kazuhiroshigeru** [UtopicUnicorns/Project_Arrow#1]
_from the Linux Mint discord server_

Just like it sounds. I'm asking for a rework on the way commands work on artemis so when running for example `!manual apt` it makes the info stay inside an expandable box and not fill the screen with all the info. same with other commands triggering long info.

**Comment by UtopicUnicorns** [comment]
Notes to self:
Copy man pages locally, spit out result.
[?tldr?](https://tldr.sh/)
[?Use Buttons?](https://github.com/UtopicUnicorns/Project_Bow/blob/00dc5f921c75736898d4ef636ec3c831eb53499f/classes/buildClass.js#L321)

**Comment by UtopicUnicorns** [comment]
Progress: [manPage](https://github.com/UtopicUnicorns/Project_Arrow/commit/f4bc565cc3c59a94c420de42e6d7c8296356bc9e)

**Comment by UtopicUnicorns** [comment]
Was no need to shorten the commands, using tldr pages.
https://github.com/UtopicUnicorns/Project_Arrow/commit/51a074794e566ffc7822b96f82e3ecf3267db1cd
